# NOTE: Additions/deletions _MUST_ be synchronized with age_from_1password.nu!
keys:
  - &leah "age1lh4sn2s9gxj2s3naqdl4wpmz3uhpd3p8l0jfy6k5hu6cu34uyygsdwadd5"
  - &focaccia "age1wtr58sze4sxjjzq9jmsq7ztkvkjakvnfzuqzn025p92htz7zsdesjpc2c8"
  
creation_rules:
  - path_regex: systems/focaccia/secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *leah
      - *focaccia
