name: CI

on:
  pull_request:
  workflow_call:
    secrets:
      CACHIX_AUTH_TOKEN:
        description: "Auth token for cachix"
  workflow_dispatch:

env:
  JUST_ARGS: --inputs-from . nixpkgs#just --command

jobs:
  build:
    name: Build outputs
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v9

      - name: Setup Cachix
        uses: cachix/cachix-action@v14
        with:
          name: pluiedev
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Run build
        run: |
          nix shell ${{ env.JUST_ARGS }} just ci

  check:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]

    name: Check flake (${{ matrix.os }})
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v9

      - name: Setup Cachix
        uses: cachix/cachix-action@v14
        with:
          name: getchoo
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Run check
        run: |
          nix shell ${{ env.JUST_ARGS }} just check
